#!/usr/bin/env bash

PGCLI_BIN="$(which pgcli)"

if [ -x "$PGCLI_BIN" ]; then
	$PGCLI_BIN -h 127.0.0.1 -p 5432 -U balance_sheet -d balance_sheet_dev
else
	echo "PGCLI_BIN must be installed."
	echo "pip install --user pgcli"
	exit 1
fi
